USE [master]
GO

CREATE DATABASE [NomadCodeTest]
	CONTAINMENT = NONE
	ON  PRIMARY 
	( NAME = N'NomadCodeTest', FILENAME = N'C:\SqlData\NomadCodeTest.mdf' , SIZE = 2MB , MAXSIZE = 2MB, FILEGROWTH = 1MB )
	LOG ON 
	( NAME = N'NomadCodeTest_log', FILENAME = N'C:\SqlData\NomadCodeTest_log.ldf' , SIZE = 2MB, MAXSIZE = 2MB , FILEGROWTH = 1MB )
GO
ALTER DATABASE [NomadCodeTest] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [NomadCodeTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NomadCodeTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NomadCodeTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NomadCodeTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NomadCodeTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [NomadCodeTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NomadCodeTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NomadCodeTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NomadCodeTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NomadCodeTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NomadCodeTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NomadCodeTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NomadCodeTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NomadCodeTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NomadCodeTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NomadCodeTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NomadCodeTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NomadCodeTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NomadCodeTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NomadCodeTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NomadCodeTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NomadCodeTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NomadCodeTest] SET RECOVERY FULL 
GO
ALTER DATABASE [NomadCodeTest] SET  MULTI_USER 
GO
ALTER DATABASE [NomadCodeTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NomadCodeTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NomadCodeTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NomadCodeTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NomadCodeTest] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NomadCodeTest] SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 2 DAYS,AUTO_CLEANUP = ON)
GO
ALTER DATABASE [NomadCodeTest] SET QUERY_STORE = OFF
GO


USE [NomadCodeTest]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

-- =================================================
--	CREATE TABLES
-- =================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VehicleType](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](256) NOT NULL
 CONSTRAINT [PK_VehicleType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Vehicle](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[VehicleTypeId] [uniqueidentifier] NOT NULL
 CONSTRAINT [PK_Vehicle] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Vehicle]
ADD FOREIGN KEY ([VehicleTypeId]) REFERENCES [VehicleType]([Id]);
GO
CREATE NONCLUSTERED INDEX [IX_Vehicle_VehicleTypeId] ON [Vehicle]([VehicleTypeId])
GO

CREATE TABLE [dbo].[VehicleImage](
	[Id] [uniqueidentifier] NOT NULL,
	[VehicleId] [uniqueidentifier] NOT NULL,
	[Content] [varbinary](max) NOT NULL
 CONSTRAINT [PK_VehicleImage] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[VehicleImage]
ADD FOREIGN KEY ([VehicleId]) REFERENCES [Vehicle]([Id]);
GO

CREATE NONCLUSTERED INDEX [IX_VehicleImage_VehicleId] ON [VehicleImage]([VehicleId])
GO

--  ====================================================
--  DATA SEEDING
--  ====================================================

DELETE FROM [dbo].[VehicleImage]
DELETE FROM [dbo].[Vehicle]
DELETE FROM [dbo].[VehicleType]

DECLARE @CoupeId uniqueidentifier = newid()
DECLARE @TruckId uniqueidentifier = newid()
INSERT INTO [dbo].[VehicleType] VALUES (@CoupeId, 'Coupe')
INSERT INTO [dbo].[VehicleType] VALUES (newid(), 'Hatchback')
INSERT INTO [dbo].[VehicleType] VALUES (newid(), 'Sedan')
INSERT INTO [dbo].[VehicleType] VALUES (@TruckId, 'Truck')

DECLARE @CorvetteId uniqueidentifier = newid()
DECLARE @CobraId uniqueidentifier = newid()
DECLARE @F150Id uniqueidentifier = newid()
INSERT INTO [dbo].[Vehicle] VALUES (@CorvetteId, 'Corvette', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (@CobraId, 'Cobra', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Coupe 3', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Coupe 4', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Coupe 5', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Coupe 6', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Coupe 7', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Coupe 8', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Coupe 9', @CoupeId)
INSERT INTO [dbo].[Vehicle] VALUES (@F150Id, 'F-150', @TruckId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Truck 2', @TruckId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Truck 3', @TruckId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Truck 4', @TruckId)
INSERT INTO [dbo].[Vehicle] VALUES (newid(), 'Truck 5', @TruckId)
GO